name: Test VOICEVOX Shared Workflow

on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  voicevox-shared-workflow:
    uses: VOICEVOX/.github/.github/workflows/shared.yml@main

    # Super Linter に必要
    permissions:
      contents: read
      packages: read
      statuses: write

    # Pythonの検証を無効化する例
    # with:
    #   super_linter_env_vars: |
    #     VALIDATE_PYTHON=false
    #     VALIDATE_PYTHON_BLACK=false
    #     VALIDATE_PYTHON_FLAKE8=false
    #     VALIDATE_PYTHON_ISORT=false
    #     VALIDATE_PYTHON_MYPY=false
    #     VALIDATE_PYTHON_PYLINT=false
